--------------------------------------------------------
--  File created - Quinta-feira-Dezembro-16-2021   
--------------------------------------------------------
DROP TABLE "EI24522"."CODIGO_POSTAL";
DROP TABLE "EI24522"."CODIGO_POSTAL";
--------------------------------------------------------
--  DDL for Table CODIGO_POSTAL
--------------------------------------------------------

  CREATE TABLE "EI24522"."CODIGO_POSTAL" 
   (	"CODPOSTAL" VARCHAR2(15 BYTE) DEFAULT NULL, 
	"LOCALIDADE" VARCHAR2(60 BYTE) DEFAULT NULL
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table CODIGO_POSTAL
--------------------------------------------------------

  CREATE TABLE "EI24522"."CODIGO_POSTAL" 
   (	"CODPOSTAL" VARCHAR2(15 BYTE) DEFAULT NULL, 
	"LOCALIDADE" VARCHAR2(60 BYTE) DEFAULT NULL
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into EI24522.CODIGO_POSTAL
SET DEFINE OFF;
Insert into EI24522.CODIGO_POSTAL (CODPOSTAL,LOCALIDADE) values ('4480-101','Vila do Conde');
--------------------------------------------------------
--  DDL for Index SYS_C008314
--------------------------------------------------------

  CREATE UNIQUE INDEX "EI24522"."SYS_C008314" ON "EI24522"."CODIGO_POSTAL" ("CODPOSTAL") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table CODIGO_POSTAL
--------------------------------------------------------

  ALTER TABLE "EI24522"."CODIGO_POSTAL" ADD PRIMARY KEY ("CODPOSTAL")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
