--------------------------------------------------------
--  File created - Quinta-feira-Dezembro-16-2021   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table PRODUTOS
--------------------------------------------------------

  CREATE TABLE "EI24522"."PRODUTOS" 
   (	"COD_PRODUTO" VARCHAR2(15 BYTE), 
	"NOME_PRODUTO" VARCHAR2(50 BYTE), 
	"DESCRICAO" VARCHAR2(70 BYTE), 
	"QTD_STOCK" NUMBER(38,0), 
	"DATA_VALIDADE" DATE, 
	"PRECO_COMPRA" NUMBER(10,2), 
	"PRECO_VENDA" NUMBER(10,2), 
	"ESTADO_PRODUTO" VARCHAR2(15 BYTE), 
	"CATEGORIA_PRODUTO" VARCHAR2(50 BYTE), 
	"NUM_FORNECEDOR" NUMBER(11,0)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table PAGAMENTOS
--------------------------------------------------------

  CREATE TABLE "EI24522"."PAGAMENTOS" 
   (	"NUM_PAGAMENTO" NUMBER(11,0), 
	"DATA_PAGAMENTO" DATE, 
	"TOTAL" NUMBER(10,2), 
	"NUM_CLIENTE" NUMBER(11,0)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table FUNCIONARIOS
--------------------------------------------------------

  CREATE TABLE "EI24522"."FUNCIONARIOS" 
   (	"ID_FUNCIONARIO" NUMBER(11,0), 
	"PRIMEIRO_NOME" VARCHAR2(50 BYTE), 
	"ULTIMO_NOME" VARCHAR2(50 BYTE), 
	"EMAIL" VARCHAR2(50 BYTE), 
	"NUM_TELEFONE" VARCHAR2(50 BYTE), 
	"CODCARGO" NUMBER(11,0)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table FORNECEDORES
--------------------------------------------------------

  CREATE TABLE "EI24522"."FORNECEDORES" 
   (	"NUM_FORNECEDOR" NUMBER(11,0), 
	"NOME" VARCHAR2(50 BYTE), 
	"PRIMEIRO_NOME" VARCHAR2(10 CHAR), 
	"ULTIMO_NOME" VARCHAR2(10 CHAR), 
	"NUM_TELEFONE" VARCHAR2(20 CHAR), 
	"RUA" VARCHAR2(50 CHAR), 
	"NPORTA" VARCHAR2(50 CHAR) DEFAULT NULL, 
	"CODPOSTAL" VARCHAR2(15 CHAR)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table ENCOMENDAS_CLIENTE
--------------------------------------------------------

  CREATE TABLE "EI24522"."ENCOMENDAS_CLIENTE" 
   (	"NUM_ENCOMENDA" NUMBER(11,0), 
	"DATA_ENCOMENDA" DATE, 
	"DATA_ENVIO" DATE, 
	"DATA_CHEGADA" DATE DEFAULT NULL, 
	"ESTADO_ENCOMENDA" VARCHAR2(15 BYTE), 
	"TOTAL_ENCOMENDA" NUMBER(11,0), 
	"ID_FUNCIONARIO" NUMBER(11,0), 
	"NUM_CLIENTE" NUMBER(11,0), 
	"NUM_PAGAMENTO" NUMBER(11,0)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table DETALHES_ENCOMENDA
--------------------------------------------------------

  CREATE TABLE "EI24522"."DETALHES_ENCOMENDA" 
   (	"NUM_ENCOMENDA" NUMBER(11,0), 
	"COD_PRODUTO" VARCHAR2(15 BYTE), 
	"NUM_LINHA_ENCOMENDA" NUMBER(6,0), 
	"QTD_PRODUTOS" NUMBER(11,0), 
	"PRECO_UNITARIO" NUMBER(10,2)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table CODIGO_POSTAL
--------------------------------------------------------

  CREATE TABLE "EI24522"."CODIGO_POSTAL" 
   (	"CODPOSTAL" VARCHAR2(15 BYTE) DEFAULT NULL, 
	"LOCALIDADE" VARCHAR2(60 BYTE) DEFAULT NULL
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table CLIENTES
--------------------------------------------------------

  CREATE TABLE "EI24522"."CLIENTES" 
   (	"NUM_CLIENTE" NUMBER(11,0), 
	"NOME" VARCHAR2(50 BYTE), 
	"PRIMEIRO_NOME" VARCHAR2(10 BYTE), 
	"ULTIMO_NOME" VARCHAR2(10 BYTE), 
	"NUM_TELEFONE" VARCHAR2(50 BYTE), 
	"RUA" VARCHAR2(50 BYTE), 
	"NPORTA" VARCHAR2(50 BYTE) DEFAULT NULL, 
	"CODPOSTAL" VARCHAR2(15 BYTE) DEFAULT NULL
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table CATEGORIAS
--------------------------------------------------------

  CREATE TABLE "EI24522"."CATEGORIAS" 
   (	"CATEGORIA_PRODUTO" VARCHAR2(50 BYTE), 
	"DESCRICAO" VARCHAR2(100 BYTE)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table CARGO
--------------------------------------------------------

  CREATE TABLE "EI24522"."CARGO" 
   (	"CODCARGO" NUMBER(11,0), 
	"TIPO" VARCHAR2(50 BYTE)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table CATEGORIAS
--------------------------------------------------------

  CREATE TABLE "EI24522"."CATEGORIAS" 
   (	"CATEGORIA_PRODUTO" VARCHAR2(50 BYTE), 
	"DESCRICAO" VARCHAR2(100 BYTE)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table FORNECEDORES
--------------------------------------------------------

  CREATE TABLE "EI24522"."FORNECEDORES" 
   (	"NUM_FORNECEDOR" NUMBER(11,0), 
	"NOME" VARCHAR2(50 BYTE), 
	"PRIMEIRO_NOME" VARCHAR2(10 CHAR), 
	"ULTIMO_NOME" VARCHAR2(10 CHAR), 
	"NUM_TELEFONE" VARCHAR2(20 CHAR), 
	"RUA" VARCHAR2(50 CHAR), 
	"NPORTA" VARCHAR2(50 CHAR) DEFAULT NULL, 
	"CODPOSTAL" VARCHAR2(15 CHAR)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table CLIENTES
--------------------------------------------------------

  CREATE TABLE "EI24522"."CLIENTES" 
   (	"NUM_CLIENTE" NUMBER(11,0), 
	"NOME" VARCHAR2(50 BYTE), 
	"PRIMEIRO_NOME" VARCHAR2(10 BYTE), 
	"ULTIMO_NOME" VARCHAR2(10 BYTE), 
	"NUM_TELEFONE" VARCHAR2(50 BYTE), 
	"RUA" VARCHAR2(50 BYTE), 
	"NPORTA" VARCHAR2(50 BYTE) DEFAULT NULL, 
	"CODPOSTAL" VARCHAR2(15 BYTE) DEFAULT NULL
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table CARGO
--------------------------------------------------------

  CREATE TABLE "EI24522"."CARGO" 
   (	"CODCARGO" NUMBER(11,0), 
	"TIPO" VARCHAR2(50 BYTE)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table CODIGO_POSTAL
--------------------------------------------------------

  CREATE TABLE "EI24522"."CODIGO_POSTAL" 
   (	"CODPOSTAL" VARCHAR2(15 BYTE) DEFAULT NULL, 
	"LOCALIDADE" VARCHAR2(60 BYTE) DEFAULT NULL
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table FUNCIONARIOS
--------------------------------------------------------

  CREATE TABLE "EI24522"."FUNCIONARIOS" 
   (	"ID_FUNCIONARIO" NUMBER(11,0), 
	"PRIMEIRO_NOME" VARCHAR2(50 BYTE), 
	"ULTIMO_NOME" VARCHAR2(50 BYTE), 
	"EMAIL" VARCHAR2(50 BYTE), 
	"NUM_TELEFONE" VARCHAR2(50 BYTE), 
	"CODCARGO" NUMBER(11,0)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table PAGAMENTOS
--------------------------------------------------------

  CREATE TABLE "EI24522"."PAGAMENTOS" 
   (	"NUM_PAGAMENTO" NUMBER(11,0), 
	"DATA_PAGAMENTO" DATE, 
	"TOTAL" NUMBER(10,2), 
	"NUM_CLIENTE" NUMBER(11,0)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table ENCOMENDAS_CLIENTE
--------------------------------------------------------

  CREATE TABLE "EI24522"."ENCOMENDAS_CLIENTE" 
   (	"NUM_ENCOMENDA" NUMBER(11,0), 
	"DATA_ENCOMENDA" DATE, 
	"DATA_ENVIO" DATE, 
	"DATA_CHEGADA" DATE DEFAULT NULL, 
	"ESTADO_ENCOMENDA" VARCHAR2(15 BYTE), 
	"TOTAL_ENCOMENDA" NUMBER(11,0), 
	"ID_FUNCIONARIO" NUMBER(11,0), 
	"NUM_CLIENTE" NUMBER(11,0), 
	"NUM_PAGAMENTO" NUMBER(11,0)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table PRODUTOS
--------------------------------------------------------

  CREATE TABLE "EI24522"."PRODUTOS" 
   (	"COD_PRODUTO" VARCHAR2(15 BYTE), 
	"NOME_PRODUTO" VARCHAR2(50 BYTE), 
	"DESCRICAO" VARCHAR2(70 BYTE), 
	"QTD_STOCK" NUMBER(38,0), 
	"DATA_VALIDADE" DATE, 
	"PRECO_COMPRA" NUMBER(10,2), 
	"PRECO_VENDA" NUMBER(10,2), 
	"ESTADO_PRODUTO" VARCHAR2(15 BYTE), 
	"CATEGORIA_PRODUTO" VARCHAR2(50 BYTE), 
	"NUM_FORNECEDOR" NUMBER(11,0)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table DETALHES_ENCOMENDA
--------------------------------------------------------

  CREATE TABLE "EI24522"."DETALHES_ENCOMENDA" 
   (	"NUM_ENCOMENDA" NUMBER(11,0), 
	"COD_PRODUTO" VARCHAR2(15 BYTE), 
	"NUM_LINHA_ENCOMENDA" NUMBER(6,0), 
	"QTD_PRODUTOS" NUMBER(11,0), 
	"PRECO_UNITARIO" NUMBER(10,2)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
REM INSERTING into EI24522.PRODUTOS
SET DEFINE OFF;
REM INSERTING into EI24522.PAGAMENTOS
SET DEFINE OFF;
REM INSERTING into EI24522.FUNCIONARIOS
SET DEFINE OFF;
REM INSERTING into EI24522.FORNECEDORES
SET DEFINE OFF;
REM INSERTING into EI24522.ENCOMENDAS_CLIENTE
SET DEFINE OFF;
REM INSERTING into EI24522.DETALHES_ENCOMENDA
SET DEFINE OFF;
REM INSERTING into EI24522.CODIGO_POSTAL
SET DEFINE OFF;
Insert into EI24522.CODIGO_POSTAL (CODPOSTAL,LOCALIDADE) values ('4480-101','Vila do Conde');
REM INSERTING into EI24522.CLIENTES
SET DEFINE OFF;
REM INSERTING into EI24522.CATEGORIAS
SET DEFINE OFF;
REM INSERTING into EI24522.CARGO
SET DEFINE OFF;
--------------------------------------------------------
--  DDL for Index SYS_C008382
--------------------------------------------------------

  CREATE UNIQUE INDEX "EI24522"."SYS_C008382" ON "EI24522"."PRODUTOS" ("COD_PRODUTO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C008389
--------------------------------------------------------

  CREATE UNIQUE INDEX "EI24522"."SYS_C008389" ON "EI24522"."PAGAMENTOS" ("NUM_PAGAMENTO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C008360
--------------------------------------------------------

  CREATE UNIQUE INDEX "EI24522"."SYS_C008360" ON "EI24522"."FUNCIONARIOS" ("ID_FUNCIONARIO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C008337
--------------------------------------------------------

  CREATE UNIQUE INDEX "EI24522"."SYS_C008337" ON "EI24522"."FORNECEDORES" ("NUM_FORNECEDOR") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C008423
--------------------------------------------------------

  CREATE UNIQUE INDEX "EI24522"."SYS_C008423" ON "EI24522"."ENCOMENDAS_CLIENTE" ("NUM_ENCOMENDA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C008432
--------------------------------------------------------

  CREATE UNIQUE INDEX "EI24522"."SYS_C008432" ON "EI24522"."DETALHES_ENCOMENDA" ("NUM_ENCOMENDA", "COD_PRODUTO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C008314
--------------------------------------------------------

  CREATE UNIQUE INDEX "EI24522"."SYS_C008314" ON "EI24522"."CODIGO_POSTAL" ("CODPOSTAL") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C008352
--------------------------------------------------------

  CREATE UNIQUE INDEX "EI24522"."SYS_C008352" ON "EI24522"."CLIENTES" ("NUM_CLIENTE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C008320
--------------------------------------------------------

  CREATE UNIQUE INDEX "EI24522"."SYS_C008320" ON "EI24522"."CATEGORIAS" ("CATEGORIA_PRODUTO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C008317
--------------------------------------------------------

  CREATE UNIQUE INDEX "EI24522"."SYS_C008317" ON "EI24522"."CARGO" ("CODCARGO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table PRODUTOS
--------------------------------------------------------

  ALTER TABLE "EI24522"."PRODUTOS" MODIFY ("COD_PRODUTO" NOT NULL ENABLE);
  ALTER TABLE "EI24522"."PRODUTOS" MODIFY ("NOME_PRODUTO" NOT NULL ENABLE);
  ALTER TABLE "EI24522"."PRODUTOS" MODIFY ("DESCRICAO" NOT NULL ENABLE);
  ALTER TABLE "EI24522"."PRODUTOS" MODIFY ("QTD_STOCK" NOT NULL ENABLE);
  ALTER TABLE "EI24522"."PRODUTOS" MODIFY ("DATA_VALIDADE" NOT NULL ENABLE);
  ALTER TABLE "EI24522"."PRODUTOS" MODIFY ("PRECO_COMPRA" NOT NULL ENABLE);
  ALTER TABLE "EI24522"."PRODUTOS" MODIFY ("PRECO_VENDA" NOT NULL ENABLE);
  ALTER TABLE "EI24522"."PRODUTOS" MODIFY ("ESTADO_PRODUTO" NOT NULL ENABLE);
  ALTER TABLE "EI24522"."PRODUTOS" MODIFY ("CATEGORIA_PRODUTO" NOT NULL ENABLE);
  ALTER TABLE "EI24522"."PRODUTOS" MODIFY ("NUM_FORNECEDOR" NOT NULL ENABLE);
  ALTER TABLE "EI24522"."PRODUTOS" ADD PRIMARY KEY ("COD_PRODUTO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table PAGAMENTOS
--------------------------------------------------------

  ALTER TABLE "EI24522"."PAGAMENTOS" MODIFY ("NUM_PAGAMENTO" NOT NULL ENABLE);
  ALTER TABLE "EI24522"."PAGAMENTOS" MODIFY ("DATA_PAGAMENTO" NOT NULL ENABLE);
  ALTER TABLE "EI24522"."PAGAMENTOS" MODIFY ("TOTAL" NOT NULL ENABLE);
  ALTER TABLE "EI24522"."PAGAMENTOS" MODIFY ("NUM_CLIENTE" NOT NULL ENABLE);
  ALTER TABLE "EI24522"."PAGAMENTOS" ADD PRIMARY KEY ("NUM_PAGAMENTO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table FUNCIONARIOS
--------------------------------------------------------

  ALTER TABLE "EI24522"."FUNCIONARIOS" MODIFY ("ID_FUNCIONARIO" NOT NULL ENABLE);
  ALTER TABLE "EI24522"."FUNCIONARIOS" MODIFY ("PRIMEIRO_NOME" NOT NULL ENABLE);
  ALTER TABLE "EI24522"."FUNCIONARIOS" MODIFY ("ULTIMO_NOME" NOT NULL ENABLE);
  ALTER TABLE "EI24522"."FUNCIONARIOS" MODIFY ("EMAIL" NOT NULL ENABLE);
  ALTER TABLE "EI24522"."FUNCIONARIOS" MODIFY ("NUM_TELEFONE" NOT NULL ENABLE);
  ALTER TABLE "EI24522"."FUNCIONARIOS" MODIFY ("CODCARGO" NOT NULL ENABLE);
  ALTER TABLE "EI24522"."FUNCIONARIOS" ADD PRIMARY KEY ("ID_FUNCIONARIO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table FORNECEDORES
--------------------------------------------------------

  ALTER TABLE "EI24522"."FORNECEDORES" MODIFY ("NUM_FORNECEDOR" NOT NULL ENABLE);
  ALTER TABLE "EI24522"."FORNECEDORES" MODIFY ("NOME" NOT NULL ENABLE);
  ALTER TABLE "EI24522"."FORNECEDORES" MODIFY ("PRIMEIRO_NOME" NOT NULL ENABLE);
  ALTER TABLE "EI24522"."FORNECEDORES" MODIFY ("ULTIMO_NOME" NOT NULL ENABLE);
  ALTER TABLE "EI24522"."FORNECEDORES" MODIFY ("NUM_TELEFONE" NOT NULL ENABLE);
  ALTER TABLE "EI24522"."FORNECEDORES" MODIFY ("RUA" NOT NULL ENABLE);
  ALTER TABLE "EI24522"."FORNECEDORES" MODIFY ("CODPOSTAL" NOT NULL ENABLE);
  ALTER TABLE "EI24522"."FORNECEDORES" ADD PRIMARY KEY ("NUM_FORNECEDOR")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table ENCOMENDAS_CLIENTE
--------------------------------------------------------

  ALTER TABLE "EI24522"."ENCOMENDAS_CLIENTE" MODIFY ("NUM_ENCOMENDA" NOT NULL ENABLE);
  ALTER TABLE "EI24522"."ENCOMENDAS_CLIENTE" MODIFY ("DATA_ENCOMENDA" NOT NULL ENABLE);
  ALTER TABLE "EI24522"."ENCOMENDAS_CLIENTE" MODIFY ("DATA_ENVIO" NOT NULL ENABLE);
  ALTER TABLE "EI24522"."ENCOMENDAS_CLIENTE" MODIFY ("ESTADO_ENCOMENDA" NOT NULL ENABLE);
  ALTER TABLE "EI24522"."ENCOMENDAS_CLIENTE" MODIFY ("TOTAL_ENCOMENDA" NOT NULL ENABLE);
  ALTER TABLE "EI24522"."ENCOMENDAS_CLIENTE" MODIFY ("ID_FUNCIONARIO" NOT NULL ENABLE);
  ALTER TABLE "EI24522"."ENCOMENDAS_CLIENTE" MODIFY ("NUM_CLIENTE" NOT NULL ENABLE);
  ALTER TABLE "EI24522"."ENCOMENDAS_CLIENTE" MODIFY ("NUM_PAGAMENTO" NOT NULL ENABLE);
  ALTER TABLE "EI24522"."ENCOMENDAS_CLIENTE" ADD PRIMARY KEY ("NUM_ENCOMENDA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table DETALHES_ENCOMENDA
--------------------------------------------------------

  ALTER TABLE "EI24522"."DETALHES_ENCOMENDA" MODIFY ("NUM_ENCOMENDA" NOT NULL ENABLE);
  ALTER TABLE "EI24522"."DETALHES_ENCOMENDA" MODIFY ("COD_PRODUTO" NOT NULL ENABLE);
  ALTER TABLE "EI24522"."DETALHES_ENCOMENDA" MODIFY ("NUM_LINHA_ENCOMENDA" NOT NULL ENABLE);
  ALTER TABLE "EI24522"."DETALHES_ENCOMENDA" MODIFY ("QTD_PRODUTOS" NOT NULL ENABLE);
  ALTER TABLE "EI24522"."DETALHES_ENCOMENDA" MODIFY ("PRECO_UNITARIO" NOT NULL ENABLE);
  ALTER TABLE "EI24522"."DETALHES_ENCOMENDA" ADD PRIMARY KEY ("NUM_ENCOMENDA", "COD_PRODUTO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table CODIGO_POSTAL
--------------------------------------------------------

  ALTER TABLE "EI24522"."CODIGO_POSTAL" ADD PRIMARY KEY ("CODPOSTAL")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table CLIENTES
--------------------------------------------------------

  ALTER TABLE "EI24522"."CLIENTES" MODIFY ("NUM_CLIENTE" NOT NULL ENABLE);
  ALTER TABLE "EI24522"."CLIENTES" MODIFY ("NOME" NOT NULL ENABLE);
  ALTER TABLE "EI24522"."CLIENTES" MODIFY ("PRIMEIRO_NOME" NOT NULL ENABLE);
  ALTER TABLE "EI24522"."CLIENTES" MODIFY ("ULTIMO_NOME" NOT NULL ENABLE);
  ALTER TABLE "EI24522"."CLIENTES" MODIFY ("NUM_TELEFONE" NOT NULL ENABLE);
  ALTER TABLE "EI24522"."CLIENTES" MODIFY ("RUA" NOT NULL ENABLE);
  ALTER TABLE "EI24522"."CLIENTES" ADD PRIMARY KEY ("NUM_CLIENTE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table CATEGORIAS
--------------------------------------------------------

  ALTER TABLE "EI24522"."CATEGORIAS" MODIFY ("CATEGORIA_PRODUTO" NOT NULL ENABLE);
  ALTER TABLE "EI24522"."CATEGORIAS" MODIFY ("DESCRICAO" NOT NULL ENABLE);
  ALTER TABLE "EI24522"."CATEGORIAS" ADD PRIMARY KEY ("CATEGORIA_PRODUTO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table CARGO
--------------------------------------------------------

  ALTER TABLE "EI24522"."CARGO" MODIFY ("CODCARGO" NOT NULL ENABLE);
  ALTER TABLE "EI24522"."CARGO" MODIFY ("TIPO" NOT NULL ENABLE);
  ALTER TABLE "EI24522"."CARGO" ADD PRIMARY KEY ("CODCARGO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table PRODUTOS
--------------------------------------------------------

  ALTER TABLE "EI24522"."PRODUTOS" ADD CONSTRAINT "CATEGORIAS_IBFK_1" FOREIGN KEY ("CATEGORIA_PRODUTO")
	  REFERENCES "EI24522"."CATEGORIAS" ("CATEGORIA_PRODUTO") ENABLE;
  ALTER TABLE "EI24522"."PRODUTOS" ADD CONSTRAINT "FORNECEDORES_IBFK_2" FOREIGN KEY ("NUM_FORNECEDOR")
	  REFERENCES "EI24522"."FORNECEDORES" ("NUM_FORNECEDOR") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table PAGAMENTOS
--------------------------------------------------------

  ALTER TABLE "EI24522"."PAGAMENTOS" ADD CONSTRAINT "PAGAMENTOS_IBFK_1" FOREIGN KEY ("NUM_CLIENTE")
	  REFERENCES "EI24522"."CLIENTES" ("NUM_CLIENTE") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table FUNCIONARIOS
--------------------------------------------------------

  ALTER TABLE "EI24522"."FUNCIONARIOS" ADD CONSTRAINT "CARGO_IBFK_1" FOREIGN KEY ("CODCARGO")
	  REFERENCES "EI24522"."CARGO" ("CODCARGO") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table FORNECEDORES
--------------------------------------------------------

  ALTER TABLE "EI24522"."FORNECEDORES" ADD CONSTRAINT "CODPOSTAL_IBFK_1" FOREIGN KEY ("CODPOSTAL")
	  REFERENCES "EI24522"."CODIGO_POSTAL" ("CODPOSTAL") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table ENCOMENDAS_CLIENTE
--------------------------------------------------------

  ALTER TABLE "EI24522"."ENCOMENDAS_CLIENTE" ADD CONSTRAINT "FUNCIONARIOS_IBFK_3" FOREIGN KEY ("ID_FUNCIONARIO")
	  REFERENCES "EI24522"."FUNCIONARIOS" ("ID_FUNCIONARIO") ENABLE;
  ALTER TABLE "EI24522"."ENCOMENDAS_CLIENTE" ADD CONSTRAINT "CLIENTES_IBFK_3" FOREIGN KEY ("NUM_CLIENTE")
	  REFERENCES "EI24522"."CLIENTES" ("NUM_CLIENTE") ENABLE;
  ALTER TABLE "EI24522"."ENCOMENDAS_CLIENTE" ADD CONSTRAINT "PAGAMENTO_IBFK_3" FOREIGN KEY ("NUM_PAGAMENTO")
	  REFERENCES "EI24522"."PAGAMENTOS" ("NUM_PAGAMENTO") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table DETALHES_ENCOMENDA
--------------------------------------------------------

  ALTER TABLE "EI24522"."DETALHES_ENCOMENDA" ADD CONSTRAINT "DETALHES_IBFK_1" FOREIGN KEY ("NUM_ENCOMENDA")
	  REFERENCES "EI24522"."ENCOMENDAS_CLIENTE" ("NUM_ENCOMENDA") ENABLE;
  ALTER TABLE "EI24522"."DETALHES_ENCOMENDA" ADD CONSTRAINT "DETALHES_IBFK_2" FOREIGN KEY ("COD_PRODUTO")
	  REFERENCES "EI24522"."PRODUTOS" ("COD_PRODUTO") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table CLIENTES
--------------------------------------------------------

  ALTER TABLE "EI24522"."CLIENTES" ADD CONSTRAINT "CODPOSTAL_IBFK_2" FOREIGN KEY ("CODPOSTAL")
	  REFERENCES "EI24522"."CODIGO_POSTAL" ("CODPOSTAL") ENABLE;
